install:
    crash_reporting:
        enabled: true
        type: "crashpad"
    game-settings:
        accountId: 3147845672314496
        modified: false
        timestamp: 0
    gameflow-patcher-lock: null
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "en_PH"
        region: "PH2"
    lcu-settings:
        accountId: 3147845672314496
        modified: false
        timestamp: 0
    patcher:
        client_migrated: true
        client_patcher_available: true
        game_migrated: true
        game_patcher_available: true
        locales:
        - "en_PH"
        toggles:
            new_client_patcher: 0
            new_game_patcher: 0
    perks-settings:
        accountId: 3147845672314496
        modified: false
        timestamp: 0
    riotclient-upgrade:
        seq-success-count: 85
        success-count: 85
    rso-auth:
        install-identifier: "bd0f69a81218554aa33a3a4053242f7f"
