page-settings:
    data:
        pages: []
        perShardPerkBooks:
            oc1:
                currentPageId: 1852882653
                pages:
                -   autoModifiedSelections: []
                    current: false
                    id: 1593583921
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isRecommendationOverride: false
                    isTemporary: false
                    isValid: true
                    lastModified: 1672875994968
                    name: "New Runes Page -4"
                    order: 0
                    primaryStyleId: 8000
                    recommendationChampionId: 0
                    recommendationIndex: -1
                    runeRecommendationId: ""
                    selectedPerkIds:
                    - 8005
                    - 9111
                    - 9104
                    - 8014
                    - 8233
                    - 8236
                    - 5005
                    - 5008
                    - 5001
                    subStyleId: 8200
            ph2:
                currentPageId: 1487781753
                pages:
                -   autoModifiedSelections: []
                    current: true
                    id: 1487781753
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isRecommendationOverride: false
                    isTemporary: false
                    isValid: true
                    lastModified: 1679064445984
                    name: "Main"
                    order: 1
                    primaryStyleId: 8000
                    recommendationChampionId: 0
                    recommendationIndex: -1
                    runeRecommendationId: ""
                    selectedPerkIds:
                    - 8010
                    - 8009
                    - 9105
                    - 8014
                    - 8444
                    - 8242
                    - 5008
                    - 5008
                    - 5003
                    subStyleId: 8400
                -   autoModifiedSelections: []
                    current: false
                    id: 2052824786
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isRecommendationOverride: false
                    isTemporary: false
                    isValid: true
                    lastModified: 1676622805819
                    name: "U.GG - Yuumi"
                    order: 1
                    primaryStyleId: 8200
                    recommendationChampionId: 0
                    recommendationIndex: -1
                    runeRecommendationId: ""
                    selectedPerkIds:
                    - 8214
                    - 8226
                    - 8210
                    - 8237
                    - 8009
                    - 8017
                    - 5008
                    - 5008
                    - 5002
                    subStyleId: 8000
        settings:
            gameplayPatchVersionSeen: "11.23"
            gameplayUpdatedPerksSeen: []
            gridModeEnabled: true
            showLongDescriptions: true
            showPresetPages: true
    schemaVersion: 5
